[workspace]
members = ["host", "ta", "ta_app", "host_app", "zkms-common"]

exclude = [
        "c_ta", "c_host", #C binaries
        ]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
debug = true
opt-level = "z"
panic = "abort"

[profile.dev]
panic = "abort"
