[package]
name = "ta-common"
version = "0.1.0"
authors = ["Zondax GmbH <support@zondax.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
optee-common = { version = "0.1.0", path = "../../../common/optee-common", features = ["alloc"] }
