[package]
name = "host-common"
version = "0.1.0"
authors = ["Zondax GmbH <support@zondax.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
serde = ["zkms-common/serde"]

[dependencies]
zkms-common = { version = "0.1", path = "../zkms-common" }
futures = { version = "0.3" }
flume = "0.10"
log = "0.4"
