[package]
name = "zkms-common"
authors = ["Zondax GmbH <support@zondax.ch>"]
description = "Common definitions for zkms-client and zkms-server"
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
version = "0.1.0" 

[features]
serde_ = ["serde", "sp-keystore/serde"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"], optional = true }
thiserror = "1"

sp-core = { version = "3.0.0" }
sp-keystore = { version = "0.9" }

[build-dependencies]
