[package]
name = "host-jsonrpc"
version = "0.1.0"
authors = ["Zondax GmbH <support@zondax.ch>"]
edition = "2018"

[features]
ci = ["zkms-jsonrpc/client"]

[dependencies]
host-common = { version = "0.1", features = ["serde"], path = "../../host-common" }
futures = { version = "0.3" }
log = "0.4"

zkms-jsonrpc = { version = "0.1", path = "../zkms" }
jsonrpc-http-server = "17"
jsonrpc-core = "17"
tokio = { version = "0.2", features = ["blocking"] }

[dev-dependencies]
jsonrpc-test = "17"
tokio = { version = "0.2", features = ["test-util", "rt-threaded", "macros"] }
env_logger = "*"
