[package]
name = "host-jsonrpc"
version = "0.1.0"
authors = ["becominginsane <francesco@zondax.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
host-common = { version = "0.1", features = ["serde"], path = "../../host-common" }
futures = { version = "0.3" }
log = "0.4"

zkms-jsonrpc = { version = "0.1", path = "../zkms" }
jsonrpc-http-server = "17"
jsonrpc-core = "17"
tokio = { version = "0.2", features = ["blocking"] }
