[package]
name = "host-ductile"
version = "0.1.0"
authors = ["becominginsane <francesco@zondax.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
host-common = { version = "0.1", features = ["serde"], path = "../../host-common" }

zkms-ductile = { version = "0.1", path = "../zkms" }
ductile = { version = "0.1", git = "https://github.com/becominginsane/ductile" }

tokio = { version = "0.2", features = ["blocking"] }
futures = "0.3"
tracing = "0.1"
