[package]
name = "zkms-common"
authors = ["Zondax GmbH <info@zondax.ch>"]
description = "Common definitions for zkms-client and zkms-server"
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
version = "0.1.0" 

[features]
serde_ = ["serde", "schnorrkel/serde"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"], optional = true }
schnorrkel = { version = "0.10", features = ["u64_backend"], default-features = false }

[build-dependencies]
