name: Build
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # So we can trigger manually
    workflow_dispatch:

env:
    QEMU_V8: 1

jobs:
    build:
        # Run this workflow in our optee self-hosted runner
        runs-on: tee-ci

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "true"
                  token: ${{ secrets.TEE_BASE_TOKEN }}

            - run: |
                  echo "SHARED_FOLDER=$HOME/qemu-shared-folder" >> $GITHUB_ENV
                  echo "OPTEE=$HOME/actions-runner/optee-qemuv8-3.12.0" >> $GITHUB_ENV

            - run: mkdir -p $SHARED_FOLDER

            - name: Build the application
              run: make

    test:
        needs: build
        runs-on: tee-ci

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "true"
                  token: ${{ secrets.TEE_BASE_TOKEN }}

            - run: |
                  echo "OPTEE=$HOME/actions-runner/optee-qemuv8-3.12.0" >> $GITHUB_ENV
                  echo "SHARED_FOLDER=$HOME/qemu-shared-folder" >> $GITHUB_ENV
                  echo "SCRIPTS=$HOME/actions-runner/scripts" >> $GITHUB_ENV

            - run: |
                  mkdir -p $SHARED_FOLDER
                  cp -r $SCRIPTS $SHARED_FOLDER/scripts

            - name: Build to application
              run: make cclean ci

            - name: Run the application tests
              run: "bash ./framework/scripts/run_ci_tests.sh"
